resolver: lts-21.25 # ghc-9.4.8

packages:
  - .

extra-deps:
- git: https://github.com/cchalmers/circuit-notation.git
  commit: 19b386c4aa3ff690758ae089c7754303f3500cc9
- clash-prelude-1.8.1
- clash-prelude-hedgehog-1.8.1
